// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byudwzewsejuopsicewd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dWR3emV3c2VqdW9wc2ljZXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NjY0NDEsImV4cCI6MjA1ODA0MjQ0MX0.N9jyxuOrUjcSdxAKOifGFnsb-wNsIeecPJGeTryu6Hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);